# options
setopt autocd              # change directory just by typing its name
#setopt correct            # auto correct mistakes
setopt interactivecomments # allow comments in interactive mode
#setopt ksharrays           # arrays start at 0
setopt magicequalsubst     # enable filename expansion for arguments of the form ‘anything=expression’
setopt nonomatch           # hide error message if there is no match for the pattern
setopt notify              # report the status of background jobs immediately
setopt numericglobsort     # sort filenames numerically when it makes sense
setopt promptsubst         # enable command substitution in prompt

# keybindings
bindkey -e                                        # emacs key bindings
#bindkey ' ' magic-space                          # do history expansion on space
bindkey '^H' backward-kill-word                   # ctrl + backspace
bindkey '^[[3;5~' kill-word                       # ctrl + delete
bindkey '^[[1~' beginning-of-line                 # home
bindkey '^[[4~' end-of-line                       # end
bindkey '^[[1;5C' forward-word                    # ctrl + ->
bindkey '^[[1;5D' backward-word                   # ctrl + <-

# completion features
autoload -Uz compinit
compinit -d ~/.cache/zcompdump
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' # case insensitive tab completion

# history
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=2000
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
#setopt share_history         # share command history data

# prompt
PROMPT='%(?.%F{green}.%F{red]})%~ %f%(!.#.$) '

# other settings
color_prompt=yes

# alias
alias ls="ls --color=auto -1F"
alias la="ls -Alh"
alias ll="ls -alhF"

alias grep="grep --color=auto"
alias egrep="egrep --color=auto"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias pg="$PAGER"
alias db="$DEBUGGER"
alias cc="$CC"
alias trace="$TRACER"
alias j="jobs"
alias h="history"
alias b="bg"
alias f="fg"
alias p="pwd"
alias u="whoami"
alias Z="exit"
alias ,="ls -1"

alias cp="cpg -g"
alias mv="mvg -g"


# plugins
source /usr/share/zsh/site-functions/zsh-syntax-highlighting.zsh