#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
picom --vsync --backend xrender -b
feh --bg-fill --randomize ~/wallpapers/*
nm-applet &
mpd
ibus-daemon -drx

wmname LG3D

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config normal_border_color \#272822
bspc config active_border_color \#75715e
bspc config focused_border_color \#a6e22e

bspc rule -a Emacs state=tiled
