#!/bin/sh

xrandr --output DP-0 --mode 2560x1440 --rate 164.83 --primary \
       --output DP-4 --mode 2560x1440 --left-of DP-0

xset -dpms

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
picom --vsync --backend xrender -b
feh --bg-fill --randomize ~/wallpapers/*
nm-applet &
mpd
ibus-daemon -drx

wmname LG3D

bspc monitor DP-4 -d 一 二 三 四 五
bspc monitor DP-0 -d 六 七 八 九 十

bspc config normal_border_color \#272822
bspc config active_border_color \#75715e
bspc config focused_border_color \#a6e22e

bspc rule -a Emacs state=tiled
