#!/bin/sh

xrandr --output LVDS-1 --mode 1600x900 --output VGA-1 --primary --mode 1920x1080 --left-of LVDS-1

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
picom --vsync --backend xrender -b
feh --bg-fill --randomize ~/wallpapers/*
nm-applet &
mpd
ibus-daemon -drx

wmname LG3D

bspc monitor VGA-1 -d 一 二 三 四 五 
bspc monitor LVDS-1 -d 六 七 八 九 十

bspc config normal_border_color \#272822
bspc config active_border_color \#75715e
bspc config focused_border_color \#a6e22e

bspc rule -a Emacs state=tiled
