#!/bin/sh

#~/.config/i3/screenlayout

# setxkbmap de

# Beeping is annoying and I don't want it
xset b off

nm-applet &
compton --vsync opengl --backend glx --blur-background &

~/.config/i3/wallpaper